POST http://localhost:3000/ingest?a=b

< /Users/iokulist/Github/okigan/awsipl/ingest/create.json

###

POST http://localhost:3000/ingest?a=b

< /Users/iokulist/Github/okigan/awsipl/ingest/list.json

###
